config/routes.rb
Tooler::Application.routes.draw do

  resources :transactions

  resources :employees do
    collection { post :import }
  end

  resources :items do
    collection { post :import }
  end

  resources :twilio do
    collection do
      get :process_sms
    end
  end

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :phone
  
  has_many :transactions, order: 'created_at DESC'
  has_many :items, through: :transactions, uniq: true

  # has_many :checkedout_items,
  #  class_name: 'Item',
  #  source: :item,
  #  through: :transactions,
  #  conditions: { transactions: { status: false } }#
  #  # uniq: true

  def checkedout_items
    items.select(&:checked_out?)
  end

  def self.search(search)
    if search
      where('name ILIKE ? OR phone ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |employee|
        csv << employee.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      employee = find_by_id(row["id"]) || new
      employee.attributes = row.to_hash.slice(*accessible_attributes)
      employee.save!
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @employees = Employee.search(params[:search])

    if @employees.class == Array
      @employees = Kaminari.paginate_array(@employees).page(params[:page]).per(50)
    else
      @employees = @employees.page(params[:page]).per(50)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
      format.csv { send_data @employees.to_csv }
      format.xls { send_data @employees.to_csv(col_sep: "\t") }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  def import
    Employee.import(params[:file])
    redirect_to root_url, notice: "Employees Imported."
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for(@employee, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :phone %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Employee Roster</h1>

<div class="well">
  <%= form_tag employees_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
</div>

<br />
<%= link_to 'Add a New Employee', new_employee_path, :class => "btn" %>
<br /><br />

<table>
  <tr>
    <th style="padding-left:30px">Name</th>
    <th style="padding-left:30px">Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td style="padding-left:30px"><%= link_to employee.name, employee %></td>
    <td style="padding-left:30px"><%= employee.phone %></td>
  </tr>
<% end %>
</table>

<%= paginate @employees %>
<br /><br />
<%= link_to "Export CSV", employees_path(format: "csv") %> |
<%= link_to "Export XLS", employees_path(format: "xls") %><br />
<%= form_tag import_employees_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/employees/new.html.erb
<h1>Add Employee to Roster</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>
<h4 style="padding-left:20px">
  <b>Phone:</b>
  <%= @employee.phone %>
</h4>

<br />

<% if @employee.checkedout_items %>
  <h3>Currently Checked-OUT Items</h3>
  <table>
    <tr>
      <th>Item ID</th>
      <th style="padding-left:30px">Asset Tag</th>
    </tr>
    <% @employee.checkedout_items.each do |transaction| %>
      <tr>
        <td style="padding-left:30px"> 
          <%= transaction.description %>
        </td>
        <td style="padding-left:30px">
          <%= transaction.assettag %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

<br /><br />

<% if @employee.transactions.count != 0 %>
  <h3>Check-IN / Check-OUT History</h3>
    <table>
      <tr>
        <th>Description</th>
        <th style="padding-left:30px">Asset Tag</th>
        <th style="padding-left:30px">Date</th>
        <th style="padding-left:30px">CheckIn/Checkout</th>
      </tr>
      <% @employee.transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.description %></td>
          <td style="padding-left:30px"><%= transaction.assettag %></td>
          <td style="padding-left:30px"><%= transaction.created_at.strftime("%A, %m/%d/%Y") %>
          <% if transaction.status == true %>  
            <td style="padding-left:30px">Check In</td>
          <% elsif transaction.status == false %>
            <td style="padding-left:30px">Check Out</td>
          <% end %>
        </tr>
      <% end %>
    </table>
  <% end %>

  <br>

<%= link_to 'Edit This Employee', edit_employee_path(@employee) %> |
<%= link_to 'Delete This Employee', @employee, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', employees_path %>