config/routes.rb
Tooler::Application.routes.draw do

  resources :transactions

  resources :employees do
    collection { post :import }
  end

  resources :items do
    collection { post :import }
  end

  resources :twilio do
    collection do
      get :process_sms
    end
  end

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :assettag, :description

  has_many :transactions
  has_many :employees, :through => :transactions

  def last_transaction
    transactions.order('created_at DESC').first
  end

  def checked_out?
    !last_transaction.status
  end

  def self.search(search)
    if search
      where('description ILIKE ? OR assettag ILIKE ?', "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end

  def self.to_csv(options= {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      employee = find_by_id(row["id"]) || new
      employee.attributes = row.to_hash.slice(*accessible_attributes)
      employee.save!
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @items = Item.search(params[:search])

    if @items.class == Array
      @items = Kaminari.paginate_array(@items).page(params[:page]).per(5)
    else
      @items = @items.page(params[:page]).per(50)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
      format.csv { send_data @items.to_csv }
      format.xls { send_data @items.to csv(col_sep: "\t") }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  def import
    Item.import(params[:file])
    redirect_to root_url, notice: "Items Imported:"
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :assettag %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Item Inventory</h1>

<div class="well">
  <%= form_tag items_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
</div>

<br />
<%= link_to 'Create New Item', new_item_path, :class => "btn" %>
<br /><br />

<table>
  <tr>
    <th style="padding-left:30px">Description</th>
    <th style="padding-left:30px">Asset ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td style="padding-left:30px"><%= link_to item.description, item %></td>
    <td style="padding-left:30px"><%= item.assettag %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= paginate @items %>
<br /><br />
<%= link_to "Export CSV", items_path(format: "csv") %> |
<%= link_to "Export XLS", items_path(format: "xls") %><br />
<%= form_tag import_items_path, multipart: true do %>
 <%= file_field_tag :file %>
 <%= submit_tag "Import" %>
<% end %>

app/views/items/new.html.erb
<h1>Add Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h1>
  <%= @item.description %>
</h1>

<h3 style="padding-left:30px">
  <b>Asset ID:</b>
  <%= @item.assettag %>
</h3>

<div class="center hero-unit">
  <% if @item.transactions.last %>
    <h2>This tool is currently 
      <% if @item.transactions.last.status == true %>
        CHECKED-IN at
      <% else %>
        CHECKED-OUT at
      <% end %>
      <%= @item.transactions.last.created_at.strftime("%A, %m/%d/%Y") %>, by
      <%= @item.transactions.last.employee.name %>, reachable at 
      <%= @item.transactions.last.employee.phone %>.
    </h2>
  <% else %>
    <h2>This item has yet to be checked out.</h2>
  <% end %>
</div>

<% if @item.transactions.count != 0 %>
  <h3 style="padding-left:30px">Other Check-in / Check-out records:</h3>
  <table>
    <tr>
      <th style="padding-left:30px">Employee</th>
      <th style="padding-left:30px">Phone Number</th>
      <th style="padding-left:30px">Date</th>
      <th style="padding-left:30px">CheckIN / CheckOUT</th>
    </tr>
    <% @item.transactions.reverse_each do |transaction| %>
      <tr>
        <td style="padding-left:30px"><%= transaction.employee.name %></td>
        <td style="padding-left:30px"><%= transaction.employee.phone %></td>
        <td style="padding-left:30px"><%= transaction.created_at.strftime("%A, %m/%d/%Y") %></td>

        <% if transaction.status == true %>
          <td style="padding-left:30px">Check In</td> 
        <% elsif transaction.status == false %>
          <td style="padding-left:30px">Check Out</td> 
        <% end %>

      </tr>
    <% end %>
  </table>
<% end %>

<br>

<%= link_to 'Edit This Item\'s Details', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>