config/routes.rb
Tooler::Application.routes.draw do

  resources :transactions

  resources :employees do
    collection { post :import }
  end

  resources :items do
    collection { post :import }
  end

  resources :twilio do
    collection do
      get :process_sms
    end
  end

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all(:order => "created_at DESC")

    if @transactions.class == Array
      @transactions = Kaminari.paginate_array(@transactions).page(params[:page]).per(50)
    else
      @transactions = @transactions.page(params[:page]).per(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def twilio_create
    @transaction = Transaction.new(:item_id => params[:Body], :employee_id => params[:From])
    @transaction.save
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :status %> 
    <%= f.input :item_id %>
    <%= f.input :employee_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
    <p class="pull-right">
      <em>(As a reminder, Check the box for 'CHECK-IN' and leave the box unchecked for "CHECK-OUT")</em>
    </p>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Edit Check-IN / Check-OUT</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Check-IN / Check-OUT History</h1>

<table>
  <tr>
    <th>Status</th>
    <th style="padding-left:30px">Date</th>
    <th style="padding-left:30px">Assettag</th>
    <th style="padding-left:30px">Item Description</th>
    <th style="padding-left:30px">By Employee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    
    <% if transaction.status == true %>
      <td><%= link_to "Check In", transaction %></td>
    <% elsif transaction.status == false %>
      <td><%= link_to "Check Out", transaction %></td> 
    <% end %>

    <td style="padding-left:30px"><%= transaction.created_at.strftime("%A, %m/%d/%Y") %>
    <td style="padding-left:30px"><%= transaction.assettag %></td>
    <td style="padding-left:30px"><%= transaction.description %></td>
    <td style="padding-left:30px"><%= transaction.name %></td>
  </tr>
<% end %>
</table>
<br />

<%= paginate @transactions %>

<%= link_to 'Enter a New Transaction Manually', new_transaction_path, :class => "btn" %>

app/views/transactions/new.html.erb
<h1>Manual Check-IN / Check-OUT</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<div class="center hero-unit">
  <h2>On
    <%= @transaction.created_at.strftime("%d/%m/%Y") %>
    <%= @transaction.name %>
    <% if @transaction.status == true %>
      CHECKED-IN
    <% else %>
      CHECKED-OUT
    <% end %>
    <%= @transaction.description %>
    (<%= @transaction.assettag %>)
  </h2>

</div>
<br>
<%= link_to 'Edit This Transaction', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>