config/routes.rb
Tooler::Application.routes.draw do

  resources :transactions

  resources :employees do
    collection { post :import }
  end

  resources :items do
    collection { post :import }
  end

  resources :twilio do
    collection do
      get :process_sms
    end
  end

  devise_for :users

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Tooler", "http://www.tooler.com" %>
     by <%= link_to "Enginuity-LLC", "http://www.enginuity-llc.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Tooler</a>
      <div class="nav-collapse">
      <ul class="nav">
        <li>
          <%= link_to 'Home',  root_path %>
        </li>
        <li>    
          <%= link_to 'About',  about_path %>
        </li>
      </ul>
      
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Add
              <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Add Item", new_item_path %></li>
              <li><%= link_to "Add Employee", new_employee_path %></li>
              <li><%= link_to "Add Transaction", new_transaction_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              View/Search
              <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Items", items_path %></li>
              <li><%= link_to "Employees", employees_path %></li>
              <li><%= link_to "Transactions", transactions_path %></li>
            </ul>
          </li>

          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>


        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tooler</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>